### ISSUE TITLE
remove duplicated field in config model

### ISSUE THREAD

**Issue by mrandi** [zalando-incubator/atlas-js-core#104]
remove https://github.com/zalando-incubator/atlas-js-core/blob/master/src/models/config_models.js#L51

**Comment by artdaw** [comment]
Maybe it's a little bit confusing but 'salesChannel' is a sales_channel provided by SDK user:
```
AtlasSDK.configure({
  client_id: 'CLIENT_ID',
  sales_channel: 'SALES_CHANNEL',
  is_sandbox: true
})
```
Config model consists of 2 parts: a configuration provided by user and a part from config-api.
