### ISSUE TITLE
Config API: use sales_channel from config API

### ISSUE THREAD

**Issue by Gregsen** [zalando-incubator/atlas-js-core#54]
Right now, we use the saleschannel provided by a client. We should use the configuration provides by the config API instead.

**Comment by artdaw** [comment]
@Gregsen #58:
> All possible SalesChannel are configured in the config API. We should use the values from there and client using the sdk can choose from the existing channels instead of confuguring their own

**Comment by mrandi** [comment]
As the relation sales channel, client and country is N:N:N.
We cannot be sure which one we should pick at runtime.
