### ISSUE TITLE
Model validation error

### ISSUE THREAD

**Issue by alsheuski** [zalando-incubator/atlas-js-core#82]
Hi. I'm trying to launch SDK example but getting the following error:

`Error: Model validation error: atlas-catalog-api is not of type object. The value is undefined`.

I use this code:
```javascript
import AtlasSDK from 'atlas-sdk-core';

AtlasSDK.configure({
    client_id: 'xxxxx_xxxxxx',
    sales_channel: 'xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx',
}).then((sdk) => {
    // sdk instance is ready to use
    const article = sdk.getArticle('AD112B0F6-A11');
    console.log('Article name: ' + article.name);
}).catch((error) => {
    console.error(error);
});
```

Can anybody help me?

**Comment by pc-alves** [comment]
Hi, @alsheuski. I will take a look into this. Sorry for the delay in getting back to you.

**Comment by pc-alves** [comment]
Hello, @alsheuski. The reason why you are getting this error is because when you run `AtlasSDK.configure(...)` you have to specify the `is_sandbox` property and set it to `true`.

This should look like the following:

```
AtlasSDK.configure({
    client_id: 'xxxxx_xxxxxx',
    sales_channel: 'xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx',
    is_sandbox: true,
})
```

Please try with this configuration.

**Comment by alsheuski** [comment]
Hello, @pc-alves. Thank you for your answer, it helped me.
